{
  "openapi":"3.0.2",
  "info": {
    "title":"GoBarber",
    "version":"1.0",
    "license": {
      "name": "MIT",
      "url": "https://raw.githubusercontent.com/DiegoVictor/gobarber-api/master/LICENSE"
    }
  },
  "servers": [
    {
      "url":"http://localhost:3333"
    }
  ],
  "paths": {
    "/sessions": {
      "post": {
        "tags": ["Sessions"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "title": "User",
                "required": [
                  "email",
                  "password"
                ],
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "email": "johndoe@example.com",
                "password": "123456"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Authenticates user, return a Bearer Token and user's id and email",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "user": {
                      "type": "object",
                      "allOf": [
                        {
                          "$ref": "#/components/schemas/User"
                        },
                        {
                          "title": "User",
                          "properties": {
                            "avatar": {
                              "type": "string"
                            },
                            "avatar_url": {
                              "type": "string"
                            }
                          }
                        }
                      ]
                    },
                    "token": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "user": {
                    "id": "c22829fa-ada5-41c4-8275-2d2e8668db63",
                    "name": "John Doe",
                    "email": "johndoe@example.com",
                    "created_at": "2021-09-28T00:38:52.889Z",
                    "updated_at": "2021-09-28T00:38:52.889Z",
                    "avatar": null,
                    "avatar_url": null
                  },
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzI3Nzg4ODEsImV4cCI6MTYzMjg2NTI4MSwic3ViIjoiYzIyODI5ZmEtYWRhNS00MWM0LTgyNzUtMmQyZTg2NjhkYjYzIn0.y58g59xzvhZ_u9bDJKD4r5bSYN-rnNfdECwdinSBPes"
                }
              }
            }
          },
          "401": {
            "description": "Email and/or password invalid",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "status": "error",
                  "message": "Email and/or password invalid"
                }
              }
            }
          }
        }
      }
    },
    "/users": {
      "post": {
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "email",
                  "name",
                  "password"
                ],
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "email": "johndoe@example.com",
                "name": "John Doe",
                "password": "123456"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Create new users",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "example": {
                  "id": "c22829fa-ada5-41c4-8275-2d2e8668db63",
                  "name": "John Doe",
                  "email": "johndoe@example.com",
                  "created_at": "2021-09-28T00:38:52.889Z",
                  "updated_at": "2021-09-28T00:38:52.889Z"
                }
              }
            }
          },
          "400": {
            "description": "Email address already in use",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "status": "error",
                  "message": "Email address already in use"
                }
              }
            }
          }
        }
      }
    },
    "/users/avatar": {
      "patch": {
        "tags": ["Users"],
        "security": [
          {
            "bearer": []
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "required": [
                  "avatar"
                ],
                "properties": {
                  "avatar": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Update user avatar",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/User"
                    },
                    {
                      "title": "User",
                      "properties": {
                        "avatar": {
                          "type": "string"
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "id": "c22829fa-ada5-41c4-8275-2d2e8668db63",
                  "name": "John Doe",
                  "email": "johndoe@example.com",
                  "avatar": "cfe492d1a0aabedb151d-15165349.png",
                  "created_at": "2021-09-28T00:38:52.889Z",
                  "updated_at": "2021-09-28T00:53:49.894Z"
                }
              }
            }
          },
          "401": {
            "description": "Only authenticated users can change avatar",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "status": "error",
                  "message": "Only authenticated users can change avatar"
                }
              }
            }
          }
        }
      }
    },
    "/password/forgot": {
      "post": {
        "tags": ["Password"],
        "security": [
          {
            "bearer": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "email": "johndoe@example.com"
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "Send to user the reset password email"
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "status": "error",
                  "message": "User does not exists"
                }
              }
            }
          }
        }
      }
    },
    "/password/reset": {
      "post": {
        "tags": ["Password"],
        "security": [
          {
            "bearer": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "password",
                  "password_confirmation",
                  "token"
                ],
                "properties": {
                  "password": {
                    "type": "string"
                  },
                  "password_confirmation": {
                    "type": "string"
                  },
                  "token": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "password": "123456",
                "password_confirmation": "123456",
                "token": "a07b30e8-7f5b-4b46-a41f-82cb41b484c9"
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "Reset user's password"
          },
          "400": {
            "description": "User not exists or the token is expired",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "examples": {
                  "User token does not exists": {
                    "value": {
                      "status": "error",
                      "message": "User token does not exists"
                    }
                  },
                  "Token exired": {
                    "value": {
                      "status": "error",
                      "message": "Token expired"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/profile": {
      "get": {
        "tags": ["Profile"],
        "security": [
          {
            "bearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "Logged in user profile",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/User"
                    },
                    {
                      "title": "User",
                      "properties": {
                        "avatar": {
                          "type": "string"
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "id": "c22829fa-ada5-41c4-8275-2d2e8668db63",
                  "name": "John Doe",
                  "email": "johndoe@example.com",
                  "created_at": "2021-09-28T00:38:52.889Z",
                  "updated_at": "2021-09-28T01:32:06.236Z",
                  "avatar": "1d92dbc7396e6e8b3b84-15165349.png"
                }
              }
            }
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "status": "error",
                  "message": "User not found"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": ["Profile"],
        "security": [
          {
            "bearer": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "name"
                ],
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "old_password": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "password_confirmation": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "name": "John Doe",
                "email": "johndoe@example.com",
                "old_password": "123456",
                "password": "123456789",
                "password_confirmation": "123456789"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Update user",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/User"
                    },
                    {
                      "title": "User",
                      "properties": {
                        "avatar": {
                          "type": "string"
                        },
                        "avatar_url": {
                          "type": "string"
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "id": "c22829fa-ada5-41c4-8275-2d2e8668db63",
                  "name": "John Doe",
                  "email": "johndoe@example.com",
                  "created_at": "2021-09-28T00:38:52.889Z",
                  "updated_at": "2021-09-28T01:49:34.139Z",
                  "avatar": "1d92dbc7396e6e8b3b84-15165349.png",
                  "avatar_url": "http://127.0.0.1:3333/uploads/1d92dbc7396e6e8b3b84-15165349.png"
                }
              }
            }
          },
          "400": {
            "description": "Error while trying to update your profile",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "examples": {
                  "You need to inform the old password to set a new one": {
                    "value": {
                      "status": "error",
                      "message": "You need to inform the old password to set a new one"
                    }
                  },
                  "Old password does not match": {
                    "value": {
                      "status": "error",
                      "message": "Old password does not match"
                    }
                  },
                  "User not found": {
                    "value": {
                      "status": "error",
                      "message": "User not found"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
  },
  "components": {
    "schemas": {
      "User": {
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      },
      "Appointment": {
        "properties": {
          "id": {
            "type": "string"
          },
          "provider_id": {
            "type": "string"
          },
          "user_id": {
            "type": "string"
          },
          "date": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      },
      "Error": {
        "properties": {
          "status": {
            "type": "string"
          },
          "message": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {
      "bearer": {
        "scheme": "bearer",
        "type": "http"
      }
    }
  }
}
